### ISSUE TITLE
What is the purpose of this repo?

### ISSUE THREAD

**Issue by dauwhe** [w3c/mathml.old#3]
As far as I know, the MathML working group does not exist at the moment. Substantive discussion of the state of math on the web happens in the [Math on the Web Community Group](https://github.com/w3c/mathonwebpages). The [W3C Math home page](https://www.w3.org/Math/) advises people to use the  <www-math@w3.org> mailing list. 

What is this repo for? Why was it restored? See thread ending at https://lists.w3.org/Archives/Member/w3c-ac-forum/2019JanMar/0013.html for discussion (W3C member-only link).

**Comment by davidcarlisle** [comment]
@dauwhe it was restored as it should never have been deleted, it was set up as a long term safe haven for the specification sources specifically because the old Working Group was closing.

There is  now a W3C Community group specifically targeting updating the MathML specification 

https://www.w3.org/community/mathml4/

See also this statement from the W3C TAG

https://github.com/w3ctag/design-reviews/issues/313#issuecomment-460523527


Currently the Community group is gathering requirements in the mathml-refresh github, and specifications will be re-synced to the W3C github repros as appropriate.

https://mathml-refresh.github.io/
